# NOTE! As of now it is required to be placed in `~/.config/lyrics/config.toml`

[general]
program_name = "LyricScribe"
check_for_updates = true

# Available modes: display (default), debug
program_mode = "display"
# Available modes: silent (default), display
logging = "silent"

[search]
depth = "both" # Available modes: match, search, both

[player]
# Any string contained in the name of the player suffices:
player = "tauon"
# player = "chromium"
# player = "mpv"

# In seconds:
position_offset = -0.52
step = 0.3
silence_timeout = 3

[display]
foreground = "#ffffff"
background = "#000000"

